//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Sync.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_JC_JCarousel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string DataSourceType { get; set; }
        public int DataSourceEntityId { get; set; }
        public int CarouselType { get; set; }
        public bool LimitedToStores { get; set; }
    }
}
